version: '3.9'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8080:8080"

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 10